parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                ceil: DoctrineExtensions\Query\Mysql\Ceil
            string_functions:
                cast: DoctrineExtensions\Query\Mysql\Cast
                greatest: DoctrineExtensions\Query\Mysql\Greatest
                lpad: DoctrineExtensions\Query\Mysql\Lpad
        mappings:
            IssuesDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/IssuesDomain/Model/Entity'
                prefix: 'eTraxis\IssuesDomain\Model\Entity'
                alias: IssuesDomain
            SecurityDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SecurityDomain/Model/Entity'
                prefix: 'eTraxis\SecurityDomain\Model\Entity'
                alias: SecurityDomain
            TemplatesDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/TemplatesDomain/Model/Entity'
                prefix: 'eTraxis\TemplatesDomain\Model\Entity'
                alias: TemplatesDomain
