parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            SecurityDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/SecurityDomain/Model/Entity'
                prefix: 'eTraxis\SecurityDomain\Model\Entity'
                alias: SecurityDomain
            TemplatesDomain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/TemplatesDomain/Model/Entity'
                prefix: 'eTraxis\TemplatesDomain\Model\Entity'
                alias: TemplatesDomain
