# Library documentation: http://tactician.thephpleague.com/
# Bundle documentation: https://github.com/thephpleague/tactician-bundle/blob/v1.0/README.md
tactician:
    commandbus:
        default:
            middleware:
                - tactician.middleware.timing
                - tactician.middleware.validator
                - tactician.middleware.locking
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler

services:

    League\Tactician\CommandBus: '@tactician.commandbus'

    tactician.middleware.timing: '@eTraxis\CommandBus\TimingMiddleware'

    eTraxis\CommandBus\TimingMiddleware:
        autowire: true

    eTraxis\CommandBus\CommandHandler\:
        autowire: true
        resource: '../../src/CommandBus/CommandHandler'
        tags: [{ name: tactician.handler, typehints: true }]

    # autowiring hints
    eTraxis\CommandBus\CommandHandler\Issues\AttachFileHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: eTraxis\CommandBus\Command\Issues\AttachFileCommand }
        arguments:
            $maxsize: '%env(FILES_MAXSIZE)%'

    # autowiring hints
    eTraxis\CommandBus\CommandHandler\Users\RegisterExternalAccountHandler:
        autowire: true
        tags:
            - { name: tactician.handler, command: eTraxis\CommandBus\Command\Users\RegisterExternalAccountCommand }
        arguments:
            $locale: '%env(ETRAXIS_LOCALE)%'
            $theme:  '%env(ETRAXIS_THEME)%'
