security:

    encoders:
        eTraxis\SecurityDomain\Model\Entity\User: bcrypt

    providers:
        etraxis_provider:
            id: LazySec\Provider\GenericUserProvider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:    ~
            guard:
                authenticators:
                    - eTraxis\SecurityDomain\Framework\Authenticator\DatabaseAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2592000
                path:     /

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/login,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN                   }
        - { path: ^/,       roles: ROLE_USER                    }
