framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations'
            - '%kernel.project_dir%/vendor/webinarium/symfony-lazysec/translations'
        fallbacks:
            - 'en'
