parameters:
    env(ETRAXIS_LOCALE): en_US

framework:
    default_locale: '%locale%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/vendor/webinarium/symfony-lazysec/translations'
        fallbacks:
            - 'en'
