parameters:
    env(ETRAXIS_THEME): azure

twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        locale: '%locale%'
        theme:  '%theme%'
        theme_color:
            azure:    '#3a8eb7'
            emerald:  '#146c64'
            humanity: '#c87629'
            mars:     '#7a403e'
