checks:
    php: true

tools:
    external_code_coverage:
        timeout: 1200
        runs: 2

filter:
    excluded_paths:
        - 'bin/*'
        - 'config/*'
        - 'public/*'
        - 'templates/*'
        - 'tests/*'
        - 'translations/*'
        - 'var/*'
        - 'vendor/*'
