build:
    dependencies:
        before:
            - 'cp config/travis/.env.mysql .env'
    tests:
        override:
            - php-scrutinizer-run

tools:
    external_code_coverage:
        timeout: 3600
        runs: 2

filter:
    excluded_paths:
        - 'assets/'
        - 'bin/'
        - 'config/'
        - 'public/'
        - 'templates/'
        - 'tests/'
        - 'translations/'
        - 'var/'
    dependency_paths:
        - 'vendor/'
