language: php

php:
    - 7.1

env:
    - DB=mysql
    - DB=pgsql

install:
    - cp config/travis/.env.$DB .env
    - cp config/travis/phpunit.$DB.xml phpunit.xml
    - composer --optimize-autoloader --no-interaction install

before_script:
    - ./bin/console --no-interaction doctrine:database:create
    - ./bin/console --no-interaction doctrine:schema:create
    - ./bin/console --no-interaction doctrine:fixtures:load

script:
    - ./bin/phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
