language: php

php:
    - 7.2

env:
    - DB=mysql
    - DB=pgsql

services:
    - mysql
    - postgresql

before_install:
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - cp config/travis/.env.$DB .env.local
    - cp config/travis/phpunit.$DB.xml phpunit.xml
    - composer --optimize-autoloader --no-interaction install

before_script:
    - ./bin/console --no-interaction doctrine:database:create
    - ./bin/console --no-interaction doctrine:schema:create
    - ./bin/console --no-interaction doctrine:fixtures:load

script:
    - ./bin/phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
