SecurityDomain:
    resource: '../../src/SecurityDomain/Framework/Controller/'
    type: annotation

SharedDomain:
    resource: '../../src/SharedDomain/Framework/Controller/'
    type: annotation

TemplatesDomain:
    resource: '../../src/TemplatesDomain/Framework/Controller/'
    type: annotation
