services:

    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

    eTraxis\SecurityDomain\Model\DataFixtures\:
        resource: '../../../src/SecurityDomain/Model/DataFixtures'
