services:

    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

    eTraxis\IssuesDomain\Model\DataFixtures\:
        resource: '../../../src/IssuesDomain/Model/DataFixtures'

    eTraxis\SecurityDomain\Model\DataFixtures\:
        resource: '../../../src/SecurityDomain/Model/DataFixtures'

    eTraxis\TemplatesDomain\Model\DataFixtures\:
        resource: '../../../src/TemplatesDomain/Model/DataFixtures'
