parameters:

    env(MAILER_ADDRESS):  ~
    env(MAILER_NAME):     eTraxis
    env(MAILER_DELIVERY): ~

    env(ETRAXIS_LOCALE): en_US
    env(ETRAXIS_THEME):  azure

    env(ETRAXIS_AUTH_FAILURES): ~
    env(ETRAXIS_LOCK_DURATION): ~

    env(LDAP_URL):    ~
    env(LDAP_BASEDN): ~

    env(GOOGLE_CLIENT_ID):     ~
    env(GOOGLE_CLIENT_SECRET): ~
    env(GOOGLE_CLIENT_DOMAIN): ~

    env(GITHUB_CLIENT_ID):     ~
    env(GITHUB_CLIENT_SECRET): ~

    env(BITBUCKET_CLIENT_ID):     ~
    env(BITBUCKET_CLIENT_SECRET): ~

    google.clientId:    '%env(GOOGLE_CLIENT_ID)%'
    github.clientId:    '%env(GITHUB_CLIENT_ID)%'
    bitbucket.clientId: '%env(BITBUCKET_CLIENT_ID)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    eTraxis\:
        resource: '../src/{IssuesDomain,SecurityDomain,TemplatesDomain}/{Framework,Model/Repository,Application/EventSubscriber,Application/Service,Application/Voter}'

    eTraxis\SharedDomain\:
        resource: '../src/SharedDomain/{Framework,Application}/*'
        exclude:  '../src/SharedDomain/Framework/{Doctrine}'

    # autowiring hints
    eTraxis\IssuesDomain\Application\Voter\IssueVoter:
        $maxsize: '%env(FILES_MAXSIZE)%'

    # autowiring hints
    eTraxis\IssuesDomain\Model\Repository\FileRepository:
        $storage: '%env(FILES_STORAGE)%'

    # autowiring hints
    eTraxis\SecurityDomain\Application\EventSubscriber\LockAccount:
        $authFailures: '%env(ETRAXIS_AUTH_FAILURES)%'
        $lockDuration: '%env(ETRAXIS_LOCK_DURATION)%'

    # autowiring hints
    eTraxis\SecurityDomain\Application\EventSubscriber\StickyLocale:
        $locale: '%env(ETRAXIS_LOCALE)%'

    # autowiring hints
    eTraxis\SecurityDomain\Framework\Authenticator\BitbucketOAuth2Authenticator:
        $clientId:     '%env(BITBUCKET_CLIENT_ID)%'
        $clientSecret: '%env(BITBUCKET_CLIENT_SECRET)%'

    # autowiring hints
    eTraxis\SecurityDomain\Framework\Authenticator\GithubOAuth2Authenticator:
        $clientId:     '%env(GITHUB_CLIENT_ID)%'
        $clientSecret: '%env(GITHUB_CLIENT_SECRET)%'

    # autowiring hints
    eTraxis\SecurityDomain\Framework\Authenticator\GoogleOAuth2Authenticator:
        $clientId:     '%env(GOOGLE_CLIENT_ID)%'
        $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
        $clientDomain: '%env(GOOGLE_CLIENT_DOMAIN)%'

    # autowiring hints
    eTraxis\SecurityDomain\Framework\Authenticator\LdapAuthenticator:
        $url:    '%env(LDAP_URL)%'
        $basedn: '%env(LDAP_BASEDN)%'

    # autowiring hints
    eTraxis\SecurityDomain\Model\DataFixtures\ProductionFixtures:
        $locale: '%env(ETRAXIS_LOCALE)%'
        $theme:  '%env(ETRAXIS_THEME)%'

    # autowiring hints
    eTraxis\SharedDomain\Application\Mailer\Mailer:
        $address: '%env(MAILER_ADDRESS)%'
        $name:    '%env(MAILER_NAME)%'
