parameters:

    locale: '%env(ETRAXIS_LOCALE)%'
    theme:  '%env(ETRAXIS_THEME)%'

    mailer.address:  '%env(MAILER_ADDRESS)%'
    mailer.name:     '%env(MAILER_NAME)%'
    mailer.delivery: '%env(MAILER_DELIVERY)%'

    files.storage: '%env(FILES_STORAGE)%'
    files.maxsize: '%env(FILES_MAXSIZE)%'

    ldap.url:    '%env(LDAP_URL)%'
    ldap.basedn: '%env(LDAP_BASEDN)%'

services:

    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

    eTraxis\:
        resource: '../src/{IssuesDomain,SecurityDomain,TemplatesDomain}/{Framework,Model/Repository,Application/EventSubscriber,Application/Service,Application/Voter}'

    eTraxis\SharedDomain\:
        resource: '../src/SharedDomain/{Framework,Application}/*'
        exclude:  '../src/SharedDomain/Framework/{Doctrine}'

    # autowiring hints
    eTraxis\IssuesDomain\Model\Repository\FileRepository:
        $storage: '%files.storage%'

    # autowiring hints
    eTraxis\SecurityDomain\Application\EventSubscriber\StickyLocale:
        $locale: '%locale%'

    # autowiring hints
    eTraxis\SecurityDomain\Framework\Authenticator\LdapAuthenticator:
        $url:    '%ldap.url%'
        $basedn: '%ldap.basedn%'

    # autowiring hints
    eTraxis\SecurityDomain\Model\DataFixtures\ProductionFixtures:
        $locale: '%locale%'
        $theme:  '%theme%'

    # autowiring hints
    eTraxis\SharedDomain\Application\Mailer\Mailer:
        $address: '%mailer.address%'
        $name:    '%mailer.name%'
