parameters:

    env(MAILER_ADDRESS):  ~
    env(MAILER_NAME):     eTraxis
    env(MAILER_DELIVERY): ~

    env(ETRAXIS_LOCALE): en_US
    env(ETRAXIS_THEME):  azure

    env(ETRAXIS_AUTH_FAILURES): ~
    env(ETRAXIS_LOCK_DURATION): ~

    env(LDAP_URL):    ~
    env(LDAP_BASEDN): ~

    env(GOOGLE_CLIENT_ID):     ~
    env(GOOGLE_CLIENT_SECRET): ~
    env(GOOGLE_CLIENT_DOMAIN): ~

    env(GITHUB_CLIENT_ID):     ~
    env(GITHUB_CLIENT_SECRET): ~

    env(BITBUCKET_CLIENT_ID):     ~
    env(BITBUCKET_CLIENT_SECRET): ~

    google.clientId:    '%env(GOOGLE_CLIENT_ID)%'
    github.clientId:    '%env(GITHUB_CLIENT_ID)%'
    bitbucket.clientId: '%env(BITBUCKET_CLIENT_ID)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    eTraxis\:
        resource: '../src/{Console,EventBus,Repository,Security,Serializer,Service,Subscriber,Twig,Validator,Voter}'

    eTraxis\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # autowiring hints
    eTraxis\DataFixtures\ProductionFixtures:
        $locale: '%env(ETRAXIS_LOCALE)%'
        $theme:  '%env(ETRAXIS_THEME)%'

    # autowiring hints
    eTraxis\EventBus\EventSubscriber\LockAccount:
        $authFailures: '%env(ETRAXIS_AUTH_FAILURES)%'
        $lockDuration: '%env(ETRAXIS_LOCK_DURATION)%'

    # autowiring hints
    eTraxis\Repository\FileRepository:
        $storage: '%env(FILES_STORAGE)%'

    # autowiring hints
    eTraxis\Security\Authenticator\BitbucketOAuth2Authenticator:
        $clientId:     '%env(BITBUCKET_CLIENT_ID)%'
        $clientSecret: '%env(BITBUCKET_CLIENT_SECRET)%'

    # autowiring hints
    eTraxis\Security\Authenticator\GithubOAuth2Authenticator:
        $clientId:     '%env(GITHUB_CLIENT_ID)%'
        $clientSecret: '%env(GITHUB_CLIENT_SECRET)%'

    # autowiring hints
    eTraxis\Security\Authenticator\GoogleOAuth2Authenticator:
        $clientId:     '%env(GOOGLE_CLIENT_ID)%'
        $clientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
        $clientDomain: '%env(GOOGLE_CLIENT_DOMAIN)%'

    # autowiring hints
    eTraxis\Security\Authenticator\LdapAuthenticator:
        $url:    '%env(LDAP_URL)%'
        $basedn: '%env(LDAP_BASEDN)%'

    # autowiring hints
    eTraxis\Service\Mailer:
        $address: '%env(MAILER_ADDRESS)%'
        $name:    '%env(MAILER_NAME)%'

    # autowiring hints
    eTraxis\Subscriber\StickyLocale:
        $locale: '%env(ETRAXIS_LOCALE)%'

    # autowiring hints
    eTraxis\Voter\IssueVoter:
        $maxsize: '%env(FILES_MAXSIZE)%'
