parameters:

    locale: '%env(ETRAXIS_LOCALE)%'
    theme:  '%env(ETRAXIS_THEME)%'

    mailer.address:  '%env(MAILER_ADDRESS)%'
    mailer.name:     '%env(MAILER_NAME)%'
    mailer.delivery: '%env(MAILER_DELIVERY)%'

services:

    _defaults:
        autowire:      true
        autoconfigure: true
        public:        false

    eTraxis\:
        resource: '../src/{IssuesDomain,SecurityDomain,TemplatesDomain}/{Framework,Model/Repository,Application/EventSubscriber,Application/Service,Application/Voter}'

    eTraxis\SharedDomain\:
        resource: '../src/SharedDomain/{Framework,Application}/*'
        exclude:  '../src/SharedDomain/Framework/{Doctrine}'

    # autowiring hints
    eTraxis\SharedDomain\Application\Mailer\Mailer:
        $address: '%mailer.address%'
        $name:    '%mailer.name%'
